# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - jobapplicationplatform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      - name: Build backend
        run: dotnet build --configuration Release

      - name: Test backend
        run: dotnet test

      - name: publish backend
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/backend-out

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/backend-out

      - name: build frontend
        run: |
          cd frontend
          dotnet build --configuration Release

      - name: publish frontend
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/frontend-out

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifact
          path: ${{env.DOTNET_ROOT}}/frontend-out

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D4EF82D50CE147BAAB1BBCDFE7E030FF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F96278D97E248BAB1F14F464E19E3F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AEB4FB7F943F4F809C6921A11731CD39 }}

      - name: Deploy backend
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "webapi"
          slot-name: "backend"
          package: ${{env.DOTNET_ROOT}}/backend-out

      - name: Deploy frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: "web"
          slot-name: "frontend"
          package: ${{env.DOTNET_ROOT}}/frontend-out
